services:
  back:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    networks:
      - rede_cord_cont

  front:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - back
    networks:
      - rede_cord_cont

networks:
  rede_cord_cont:
    driver: bridge
