services:
  mysql:
    image: mysql:8.0
    container_name: mysql_livraria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: livraria_lab01
    ports:
      - "3307:3306"
    volumes:
      - mysql_livraria_data:/var/lib/mysql

volumes:
  mysql_livraria_data: