services:
  mysql:
    image: mysql:8.0
    container_name: mysql_loja
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loja
    ports:
      - "3307:3306"
    volumes:
      - mysql_loja_data:/var/lib/mysql

volumes:
  mysql_loja_data: